const texts = {
  'Lorem ipsum dolor sit amet': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt exercitationem quaerat minus quisquam nisi consequatur provident iure officiis inventore expedita libero dolor praesentium cupiditate illo, aut earum voluptatibus ea fugit magnam iusto saepe perferendis commodi impedit quo?',
  'Modi eligendi quae, rem, libero': 'Modi eligendi quae, rem, libero, praesentium nesciunt iure possimus eum odit repudiandae ipsum. Quibusdam, exercitationem. Quod ipsam minima ullam, odit voluptatem dolorem asperiores enim officiis dolores veritatis aliquid eaque consequuntur? Optio illum alias officia id. Error dolores blanditiis quo ipsam tenetur dolore eveniet optio ex eligendi voluptates obcaecati sapiente earum voluptatibus dicta, quae dolor odit exercitationem rem. Tempore numquam, cupiditate rem, animi quo a possimus expedita architecto ducimus explicabo temporibus eius obcaecati, atque vero nobis soluta optio velit illum alias asperiores et.',
  'Minus excepturi nostrum': 'Minus excepturi nostrum, est repellendus modi atque magni! Commodi porro iusto veritatis, voluptates ex sequi cum et officia fugiat vel ducimus reprehenderit voluptatem eos quo repellat doloribus temporibus ratione cupiditate? Ad sit ea nostrum mollitia veniam ipsum? Cum dolorum fugiat et id labore ducimus deserunt? Possimus aut ducimus cum dicta illo illum amet culpa tempora rerum odio? Itaque iusto ipsam maxime officia animi eum eveniet, adipisci nisi in, ad est voluptatibus mollitia officiis commodi similique blanditiis nulla praesentium voluptates. Enim ipsa possimus dolores unde cumque, recusandae beatae sint sit totam?',
  'Ducimus architecto vel': 'Ducimus architecto vel, temporibus veniam hic error quas consequatur voluptatem accusantium reiciendis officia. Labore modi beatae corporis commodi sapiente reiciendis doloribus sequi alias quibusdam! Aliquam architecto ullam nemo illum quas maxime tempora ipsam deserunt, facere eaque voluptatem neque assumenda quo cum minima quaerat enim, ipsa error praesentium libero sed repellendus beatae? Harum ipsum, sint delectus perferendis suscipit beatae repudiandae quidem dolorem! Accusantium asperiores ex consequuntur error placeat praesentium atque iusto maiores quae veniam animi corrupti, expedita odit vel aut voluptatem.',
  'Sit omnis eos atque in tempora': 'Sit omnis eos atque in tempora repudiandae nemo nihil illo beatae inventore similique nisi, magni iure quisquam laudantium ea placeat ipsa cum natus nostrum. Temporibus porro expedita quod harum repellat nam aut reprehenderit, ipsum delectus ea, veniam vel. Amet mollitia aspernatur accusantium rerum quis beatae, distinctio autem nihil nam. Tempora accusamus rem quis aut culpa odio? Sed minus possimus molestiae consequatur laborum fugit maxime exercitationem sint eum magnam amet cupiditate dolorum fuga pariatur nulla ea earum magni, eligendi omnis voluptatibus?',
  'Alias, iste quam voluptates': 'Alias, iste quam voluptates, modi consequatur accusantium, officiis illum explicabo eos beatae est aliquid aperiam. Eos dolor eum nulla repellendus officiis. Inventore, eos adipisci! Exercitationem numquam iusto adipisci libero aliquam nostrum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum enim, ratione deserunt labore architecto minus reprehenderit magnam. Nam corrupti nihil iste officiis aperiam illum voluptatum cupiditate animi beatae est modi ipsam voluptas, commodi blanditiis hic minus?',
  'Nulla nihil ratione omnis': 'Nulla nihil ratione omnis ea eveniet distinctio fugiat dolor, sed soluta iusto a quod sequi? Odio corrupti repellendus a hic maiores ea eveniet saepe, provident sapiente amet, ipsum placeat voluptate dicta praesentium quasi ducimus ratione pariatur, dignissimos vero suscipit earum quod qui ipsa accusamus! Maxime, ea nesciunt? Fugit, porro cum. Asperiores excepturi dolorum ad ipsam porro exercitationem recusandae, corporis, magni molestias praesentium enim. Temporibus dolore cumque pariatur reprehenderit architecto inventore id!',
  'Consequatur, eius odit assumenda a at': 'Consequatur, eius odit assumenda a at, enim dolore temporibus nulla unde, quae aut sequi suscipit iure mollitia architecto! Expedita quia porro aspernatur dolor neque inventore rerum temporibus eveniet, nihil eos minus, dolore consectetur maxime aliquid excepturi laboriosam hic fuga cupiditate autem libero repellat nisi. Officia, eveniet pariatur neque minus est ab quae sint accusamus vitae laborum eos perspiciatis. Quod, tempora reiciendis optio, rerum nisi incidunt cupiditate totam veniam consectetur repellendus recusandae dolor voluptate vitae fugit? Accusamus fugiat ullam culpa, cupiditate modi reiciendis laboriosam delectus praesentium! Optio et quidem incidunt voluptatum illum mollitia consectetur.'
}

export default texts
